# https://taskfile.dev/#/installation
version: '3'

silent: true

tasks:
  default:
    task -l

  unit:
    cmds:
      - echo "Unit..."
      - go test -coverprofile=coverage.txt -covermode=atomic ./...

  unit-v:
    cmds:
      - echo "Unit -v ..."
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

  # опасная команда - живучие процессы запускает
  unit-f:
    cmds:
      - echo "Unit -fuzz ..."
      - go test -fuzz ./...
      # kill $(ps aux | grep 'es.test' | awk '{print $2}') - через Ctrl+C процессы не убиваются

  cover:
    cmds:
      - echo "Cover..."
      - go tool cover -func=coverage.txt

  cover-h:
    cmds:
      - echo "Cover html..."
      - go tool cover -html=coverage.txt

  lint:
    cmds:
      - echo "Lint..."
      - golangci-lint run ./... --skip-dirs some-root-dir-name
